apiVersion: apps/v1
kind: Deployment
metadata:
 name: tsato-cluster
spec:
 replicas: 2
 selector:
   matchLabels:
     name: tsato-cluster
 template:
   metadata:
     labels:
       name: tsato-cluster
   spec:
     containers:
     - name: tsato-cluster
       image: gcr.io/pra-cloud/tsato-cluster:latest
       ports:
       - containerPort: 8080
         protocol: TCP
 revisionHistoryLimit: 100

